# Generated by Django 5.1.3 on 2024-11-21 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('bio', models.TextField(verbose_name='')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='')),
                ('updated', models.DateField(auto_now=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Auther',
                'verbose_name_plural': 'Authers',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('featured', models.BooleanField(default=False, verbose_name='')),
                ('order', models.IntegerField(default=1, verbose_name='')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='')),
                ('updated', models.DateField(auto_now=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.JSONField(default=dict, verbose_name='')),
                ('total', models.FloatField(verbose_name='')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='')),
                ('updated', models.DateField(auto_now=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('subtitle', models.TextField(null=True, verbose_name='')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='')),
                ('order', models.IntegerField(default=1, verbose_name='')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='')),
                ('updated', models.DateField(auto_now=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('short_description', models.TextField(null=True, verbose_name='')),
                ('description', models.TextField(null=True, verbose_name='')),
                ('image', models.ImageField(upload_to='', verbose_name='')),
                ('price', models.FloatField(verbose_name='')),
                ('featured', models.BooleanField(default=False, verbose_name='')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='')),
                ('updated', models.DateField(auto_now=True, verbose_name='')),
                ('auther', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.auther', verbose_name='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.category', verbose_name='')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='')),
                ('prder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.order', verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='')),
            ],
        ),
    ]
