# Generated by Django 5.0.4 on 2024-11-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='', verbose_name='pdf_file'),
        ),
    ]
