# Generated by Django 5.1.3 on 2024-11-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_customer_remove_order_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.JSONField(default=dict, verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.JSONField(default=dict, verbose_name='total'),
        ),
    ]
