# Generated by Django 5.1.3 on 2024-11-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50, verbose_name='session')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('items', models.JSONField(default=dict, verbose_name='items')),
                ('customer', models.JSONField(default=dict, verbose_name='customer')),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Comleted')], default=0, verbose_name='status')),
                ('payment_method', models.IntegerField(choices=[(0, 'Stripe'), (1, 'Paypal')], default=None, verbose_name='paymentmethod')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='')),
                ('updated', models.DateField(auto_now=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
